name: customized_country_phone_picker
description: Customizable Flutter phone input country picker (sheet/dialog), EN
  & AR names, validation, dial modes, themed search.
version: 0.3.2
homepage: https://github.com/MustafaYounis27/customized_country_phone_picker
repository: https://github.com/MustafaYounis27/customized_country_phone_picker
issue_tracker: https://github.com/MustafaYounis27/customized_country_phone_picker/issues
topics:
  - phone
  - country-picker
  - country-phone-picker
  - input
  - widget

environment:
  sdk: ^3.7.0
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
